# Site settings
author: Adam Beatty
title: Flatiron Blog
header-img: img/home-bg.png
email: adam.t.beatt@gmail.com
copyright_name: Adam Beatty
description: > # this means to ignore newlines until "baseurl:"
  Important Takeaways from a FT Student
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  atBeatty

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
